<?php /** 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5c7b5d0a8cc2881127fbfb10
*
* You will get 10% discount for each one of your friends
* 
*/
?>
<?php
	require_once './db/dbS2_dbManager.php';
	
/*
 * SCHEMA DB Reports
 * 
	{
		Date: {
			type: 'Date'
		},
		Description: {
			type: 'Boolean'
		},
		//RELAZIONI
		
		
		//RELAZIONI ESTERNE
		
		
	}
 * 
 */


//CRUD METHODS


//CRUD - CREATE


$app->post('/reports',	function () use ($app){

	$body = json_decode($app->request()->getBody());
	
	$params = array (
		'Date'	=> isset($body->Date)?$body->Date:'',
		'Description'	=> isset($body->Description)?$body->Description:'',
			);

	$obj = makeQuery("INSERT INTO reports (_id, Date, Description )  VALUES ( null, :Date, :Description   )", $params, false);

	
	echo json_encode($body);
	
});
	
//CRUD - REMOVE

$app->delete('/reports/:id',	function ($id) use ($app){
	
	$params = array (
		'id'	=> $id,
	);

	makeQuery("DELETE FROM reports WHERE _id = :id LIMIT 1", $params);

});
	
//CRUD - GET ONE
	
$app->get('/reports/:id',	function ($id) use ($app){
	$params = array (
		'id'	=> $id,
	);
	
	$obj = makeQuery("SELECT * FROM reports WHERE _id = :id LIMIT 1", $params, false);
	
	
	
	echo json_encode($obj);
	
});
	
	
//CRUD - GET LIST

$app->get('/reports',	function () use ($app){
	makeQuery("SELECT * FROM reports");
});


//CRUD - EDIT

$app->post('/reports/:id',	function ($id) use ($app){

	$body = json_decode($app->request()->getBody());
	
	$params = array (
		'id'	=> $id,
		'Date'	    => isset($body->Date)?$body->Date:'',
		'Description'	    => isset($body->Description)?$body->Description:''	);

	$obj = makeQuery("UPDATE reports SET  Date = :Date,  Description = :Description   WHERE _id = :id LIMIT 1", $params, false);

	
	echo json_encode($body);
    	
});


/*
 * CUSTOM SERVICES
 *
 *	These services will be overwritten and implemented in  Custom.js
 */

			
?>