/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5c7b5d0a8cc2881127fbfb10
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
// Import Services
import { ReportsService } from '../../services/reports.service';
// Import Models
import { Reports } from '../../domain/s2_db/reports';

// START - USED SERVICES
/**
* ReportsService.delete
*	@description CRUD ACTION delete
*	@param ObjectId id Id
*
* ReportsService.list
*	@description CRUD ACTION list
*
*/
// END - USED SERVICES

/**
 * This component shows a list of Reports
 * @class ReportsListComponent
 */
@Component({
    selector: 'app-reports-list',
    templateUrl: './reports-list.component.html',
    styleUrls: ['./reports-list.component.css']
})
export class ReportsListComponent implements OnInit {
    list: Reports[];
    search: any = {};
    idSelected: string;
    constructor(
        private reportsService: ReportsService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.reportsService.list().subscribe(list => this.list = list);
    }

    /**
     * Select Reports to remove
     *
     * @param {string} id Id of the Reports to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected Reports
     */
    deleteItem() {
        this.reportsService.remove(this.idSelected).subscribe(data => this.list = this.list.filter(el => el._id !== this.idSelected));
    }

}
